### ISSUE TITLE
Add customer docker volume mappings

### ISSUE THREAD

**Issue by nickgrealy** [mountain-pass/hooked#5]
e.g. to secret files stored in HOME

```
scripts:
  upload:
    $image: mountainpass/s3cmd
    $volumes:
      - $HOME/.hooked/.s3cfg-nofulabs:/root/.s3cfg
```
